### ISSUE TITLE
fatal errors are printed in sys output and MalformedByteSequenceException

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#10]
I'm getting these errors:

[Fatal Error] log.xml:510:1: XML document structures must start and end within the same entity.
[Fatal Error] log.xml:168:1: XML document structures must start and end within the same entity.
Execption occured: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 2-byte UTF-8 sequence.

Please remove all output and catch each error properly categorizing it in the report.

**Comment by keshavnangare** [comment]
Fixed with this commit 1d39f4de835ae35514451f2129b44a9a5cdc8820
