### ISSUE TITLE
update this code so it can work with the new reporting (>TE 5.0)

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#12]

**Comment by bermud** [comment]
generate a CSV (for now - last month)
name of test | date it was run | user | result |

**Comment by keshavnangare** [comment]
@bermud

Teamengine changes will not affect to this te-statistics code. I have checked the code and it worked fine.

You can run TEReport class which will generate the result file with the following details:
`userName|session|date|year|month|testName|overallResult`
Currently it the result is in the text file but I will update the code which will generate the CSV file.

Command: `java -cp stats-1.0-SNAPSHOT-with-deps.jar org.opengis.te.stats.TEReport /path/to/users`

Let me know if you face any issue.

**Comment by keshavnangare** [comment]
Added minor change(in master) which will help to generate csv file.

Commit: 2ccbb55264d971df0e9ec012af4dd28b794a7981

**Comment by dstenger** [comment]
@keshav-nangare Can you please provide some screenshots of your results? Please attach them to this issue.

**Comment by keshavnangare** [comment]
Following result is appearing:
   
   
userName | session | date | year | month | testName | overallResult
-- | -- | -- | -- | -- | -- | --
ogctest | s0001 | 2018/12/05 18:30:14 | 2018 | 12 | WFS20 | FAIL
ogctest | s0002 | 2018/12/05 19:01:07 | 2018 | 12 | WFS20 | FAIL
ogctest | s0003 | 2018/12/05 19:25:53 | 2018 | 12 | WFS20 | FAIL
ogctest | s0004 | 2018/12/05 19:33:04 | 2018 | 12 | WFS20 | FAIL
ogctest | s0005 | 2018/12/05 19:47:51 | 2018 | 12 | GML321 | PASS
ogctest | s0006 | 2018/12/05 19:57:29 | 2018 | 12 | WFS20 | Not Found
ogctest | s0007 | 2018/12/05 22:02:30 | 2018 | 12 | WFS20 | Not Found
ogctest | s0008 | 2018/12/05 22:41:09 | 2018 | 12 | WFS20 | FAIL
ogctest | s0009 | 2018/12/06 15:16:03 | 2018 | 12 | WMS130 | Not Found
ogctest | s0010 | 2018/12/06 15:57:44 | 2018 | 12 | WMS130 | INHERITED FAILURE
ogctest | s0011 | 2018/12/06 18:10:16 | 2018 | 12 | WFS20 | FAIL
ogctest | s0012 | 2018/12/07 12:39:08 | 2018 | 12 | GML321 | PASS
ogctest | s0013 | 2018/12/07 15:14:59 | 2018 | 12 | GML321 | PASS
ogctest | s0014 | 2018/12/07 15:17:06 | 2018 | 12 | GML321 | PASS
ogctest | s0015 | 2018/12/07 15:30:02 | 2018 | 12 | WFS20 | FAIL
ogctest | s0016 | 2018/12/07 15:43:32 | 2018 | 12 | WMS130 | FAIL
ogctest | s0017 | 2018/12/07 15:59:36 | 2018 | 12 | WMS130 | PASS
ogctest | s0018 | 2018/12/07 16:05:43 | 2018 | 12 | WMS130 | INHERITED FAILURE
ogctest | s0019 | 2018/12/10 11:43:16 | 2018 | 12 | WFS20 | FAIL
ogctest | s0020 | 2018/12/10 12:40:28 | 2018 | 12 | WFS20 | FAIL
ogctest | s0021 | 2018/12/10 13:22:04 | 2018 | 12 | WFS20 | FAIL
ogctest | s0022 | 2018/12/10 13:24:27 | 2018 | 12 | WFS20 | FAIL
ogctest | s0023 | 2018/12/10 15:18:13 | 2018 | 12 | WMS-Client130 | FAIL
ogctest | s0024 | 2018/12/10 16:14:20 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0025 | 2018/12/10 18:21:08 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0026 | 2018/12/11 12:31:55 | 2018 | 12 | WMS-Client130 | FAIL
ogctest | s0027 | 2018/12/11 13:00:45 | 2018 | 12 | WMS-Client130 | FAIL
ogctest | s0028 | 2018/12/11 13:06:02 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0029 | 2018/12/11 14:10:49 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0030 | 2018/12/11 14:36:51 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0031 | 2018/12/11 16:45:03 | 2018 | 12 | WMS-Client130 | FAIL
ogctest | s0032 | 2018/12/11 17:18:17 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0033 | 2018/12/11 18:00:58 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0034 | 2018/12/11 18:44:45 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0035 | 2018/12/11 19:02:37 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0036 | 2018/12/11 19:35:36 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0037 | 2018/12/11 19:50:07 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0038 | 2018/12/11 21:43:11 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0039 | 2018/12/11 21:50:09 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0040 | 2018/12/11 22:13:14 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0041 | 2018/12/12 13:36:25 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0042 | 2018/12/12 14:27:37 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0043 | 2018/12/12 15:45:34 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0044 | 2018/12/12 16:46:39 | 2018 | 12 | WMS-Client130 | Not Found
ogctest | s0045 | 2018/12/12 16:58:16 | 2018 | 12 | WMS-Client130 | Not Found

**Comment by dstenger** [comment]
Code was updated.
