### ISSUE TITLE
Create statistics of Prod environment

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#13]

**Comment by bermud** [comment]
Create a copy of the user's session folder and work on the copied version.

**Comment by bermud** [comment]
We can do a CSV and a simple visualization of test sessions (e.g. a pie chart by test name).

**Comment by dstenger** [comment]
Copy will be provided to @keshav-nangare.

**Comment by dstenger** [comment]
Copy was provided.
