### ISSUE TITLE
Define workflow how to generate statistics regularly

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#14]

**Comment by keshavnangare** [comment]
The following workflow will be used to generate statistics:
1. We will define a REST API to get teamengine statistics in teamengine webapp.
2. After hitting the endpoint, it will check for the config file in the TE_BASE directory to get a list of available test suites that will be used in the generation of statistics report.
3. It will generate two types of HTML report:
    1. `index.html`: Overall teamengine statistics about following for the current year
        1. Number of tests executed per standard (pie-graph)
        2. Number of tests and users executed per month (bar_line-graph)
        3. Number of users per test suite (pie-graph)
        4. Table of test suite specific report
    2. `{test_suite_name}-stats.html`: It will contain the graphs about for the current year
        1. Number of times the test suite executed per month (line-graph)
        2. Number of users executed the test suite per month  (line-graph)
        3. Status(pass/fail/incomplete) of the test suite for per month (bar-graph)
        4. Status of the test suite containing information of failed test after clicking on failure status (pie-graph)
4. These all HTML reports will be returned as a zip file.
