### ISSUE TITLE
Implement workflow to generate statistics regularly

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#15]

**Comment by keshavnangare** [comment]
According to the workflow defined in the [comment](https://github.com/opengeospatial/teamengine-statistics/issues/14#issuecomment-704315696), I have generated the TeamEngine statistics report. Please find the report file below:
[TE_Statistics_2020-10-08_19-39-31.zip](https://github.com/opengeospatial/teamengine-statistics/files/5353168/TE_Statistics_2020-10-08_19-39-31.zip)

**Comment by keshavnangare** [comment]
Please find the statistics report:
[TE_Statistics_2020-10-19_14-29-49.zip](https://github.com/opengeospatial/teamengine-statistics/files/5414059/TE_Statistics_2020-10-19_14-29-49.zip)

**Comment by keshavnangare** [comment]
The workflow is implemented in teamengine webapp so the changes will be there in the teamengine repository.

Please find the PR raised for the changes https://github.com/opengeospatial/teamengine/pull/439
