### ISSUE TITLE
Find tool to visualize statistics

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#16]

**Comment by dstenger** [comment]
Possible tools:
- Excel/ LibreOffice Calc
- Google Charts: https://developers.google.com/chart/

**Comment by dstenger** [comment]
@keshav-nangare Any progress on this issue? Can you please list your preferred tools?

**Comment by keshavnangare** [comment]
We are using the HighChart tool which is providing the javascript library with lots of different charts.
I have created the template with pie chart and bar chart.
Here is the reference link: https://www.highcharts.com/demo
