### ISSUE TITLE
Generate visualized statistics

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#17]
Please create following statistics:

- Total test runs per month in 2019.
- Runs per test suite in 2019.

Thus, in general, all test runs before 2019 can be ignored.

**Comment by dstenger** [comment]
@keshav-nangare 
I updated the requirements of this task in the description of this issue.
Can you please send the visualized statistics to me via email?

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you for the good work!
Can you please create two further statistics (test runs is replaced by number of users)?
- Total number of users per month in 2019.
- Number of users per test suite in 2019.

Please use those two sentences as header as well.

**Comment by keshavnangare** [comment]
Updated the script to add year value dynamically into report title.
