### ISSUE TITLE
Create more detailed report per standard

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#19]
1) time series per month by unique user 
2) time series per month by runs
3) success and failures and incomplete(other than success and failure) by runs per month
4) when clicking on failures then see the reasons in a pie chart - by conformance class or by test

General failure: If it passes the required minimum conformance class, then it shoes as passed

And another more detailed report about failures: by conformance class or test.

Please start with WFS 2.0 and KML 2.2.

**Comment by keshav-nangare** [comment]
Added year value dynamically into report title.

**Comment by keshavnangare** [comment]
Changed titles:

1. time series per month by unique user ==> Number of users executed the WFS test per month in 2019
3. success and failures by runs per month ==> WFS 2.0 standard success and failures by runs per month in 2019

**Comment by keshavnangare** [comment]
Added all three reports in the statistics HTML report.

**Comment by dstenger** [comment]
Thank you, can you also create test suite specific report for KML 2.2?

**Comment by keshavnangare** [comment]
Sure, I will create a report for KML 2.2.

**Comment by keshavnangare** [comment]
- Created the report for KML 2.2
- We need to discuss point no 4 from the first comment.

**Comment by dstenger** [comment]
> General failure: If it passes the required minimum conformance class, then it shoes as passed

Minimum conformance classes have not been configured on Production environment, yet.

**Comment by dstenger** [comment]
Improvements:
- Pie charts: Sort pies by size (from large to small).

**Comment by lgoltz** [comment]
Blocked by #22

**Comment by keshavnangare** [comment]
The statistics generation report contains the following charts:

- Main Report
  1. Tests run per standard (Pie chart)
  2. Total number of test and users per month (Bar-Line chart)
  3. Number of users per test suite (Pie chart)
  4. Statistics table of each standard (Name and link)

- Each Standard Report
  1. Standard run per month (Line chart)
  2. Number of users executed standard per month (Line chart)
  3. Passing, failing, and incomplete tests run per month (Bar Chart)
  4. Passing, failing, and incomplete tests run year (Pie Chart)
      1. If the test suite is based on TestNG, we click on failing tests new pie chart will be generated with the name of failure tests.

**Comment by dstenger** [comment]
@keshav-nangare Can you please check the security hint in https://github.com/opengeospatial/teamengine/pull/439?
