### ISSUE TITLE
Write short manual how to execute statistics scripts

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#20]
Aim: Statistics for Beta environment shall be created on server directly.

**Comment by bermud** [comment]
I suggest to have a well written shell script and document inside the script. Suggest to have two inputs:
1) local path to the users folder
2) folder to push the generated content (html, images, etc.)

+ add date of generation to the report

**Comment by keshavnangare** [comment]
- Created the shell script to generate the HTML statistics report. (The shell script has help section as well)
- The report will be generated inside the result directory.
- Also added the timestamp to the report file.

**Comment by keshavnangare** [comment]
# Steps to generate the HTML statistics report
- Build the project with maven
  - `mvn clean install`
- Run shell script
  - `./test_statistics.sh -u ~/your_dir_path/users -c ~/your_dir_path/config.xml`
     -u : Local path to users directory
     -c : Local path to config.xml file

Note: 
       - The config.xml file should contain all the test suite according to the beta or prod. 
       - If one of the test suite info is missing in config file then the data of that particular test suite will not appear in the report.
