### ISSUE TITLE
Find open source tool to create visualized statistics

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#21]

**Comment by keshavnangare** [comment]
Following are the open source tool:

- Chart.js  Reference: https://www.chartjs.org/samples/latest/
          The Chart.js has pie chart, bar chart and line chart as well. But I am not sure about the drilldown pie chart, we need to explore on this part.

**Comment by dstenger** [comment]
License of Chart.js is `MIT License` (https://github.com/chartjs/Chart.js/blob/master/LICENSE.md).

**Comment by dstenger** [comment]
A prototype for Chart.js is created: #22
