### ISSUE TITLE
Migrate visualized statistics to Chart.js

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#22]
Please create a prototype to review the results.

Chart.js was evaluated in  #21.

**Comment by dstenger** [comment]
Next task: Continue migration.

**Comment by dstenger** [comment]
@keshav-nangare Can you please attach the current results to this issue?

**Comment by keshavnangare** [comment]
@dstenger 

Please find below the current report and still I am working on the drill-down pie chart & will finish this report tomorrow and once again will share the whole report with you.

[new_te_statistics.html.txt](https://github.com/opengeospatial/teamengine-statistics/files/3468158/new_te_statistics.html.txt)

**Comment by keshavnangare** [comment]
Updated the chart with following:

- The pie chart is displayed in sorted order by values.
- Updated the colorscheme CDN URL instead of file import.

New report:
[te_statistics.html.txt](https://github.com/opengeospatial/teamengine-statistics/files/3478261/te_statistics.html.txt)

**Comment by dstenger** [comment]
@keshav-nangare Please use same data as used for #19.

**Comment by dstenger** [comment]
@keshav-nangare Are there any new results?

**Comment by keshavnangare** [comment]
@dstenger 

Please find attached a new report with real values.

[te_statistics.html.txt](https://github.com/opengeospatial/teamengine-statistics/files/3524082/te_statistics.html.txt)

**Comment by dstenger** [comment]
@keshav-nangare Report looks good. Can you please migrate the other statistics as well?

**Comment by keshavnangare** [comment]
Following things need to update to migrate other statistics:
- [x] Update Java code to provide the inputs to XSL according to the new requirement.
- [x] Updated the XSL with other charts as per the new report.

Note: We are using the same steps to runs this script. https://github.com/opengeospatial/teamengine-statistics/issues/20#issuecomment-500843595

**Comment by keshavnangare** [comment]
@dstenger 

I have migrated all the statistics report to the new report. Can you please review the below report and let me know if you have any suggestion?

[TE-StatisticsReport-2019-08-30_14-19-34.html.txt](https://github.com/opengeospatial/teamengine-statistics/files/3559377/TE-StatisticsReport-2019-08-30_14-19-34.html.txt)
