### ISSUE TITLE
Create usage statistics for ets-ogcapi-features10

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine-statistics#24]
Test suite: https://github.com/opengeospatial/ets-ogcapi-features10

@keshav-nangare We must coordinate how to transfer the data.

**Comment by ghobona** [comment]
Related to https://github.com/opengeospatial/teamengine-statistics/issues/22

**Comment by keshavnangare** [comment]
This is already covered in the issue: #15
