### ISSUE TITLE
the count is not correct

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#5]
When running the code, I get the same number for Last Month, Last 3 Months and Last Year.

Test Name: Catalogue Service - Web (CSW)_3.0.0
Last Month:40   |   Last 3 Months:40        |   Last Year:40    |   All Times:40

Test Name: Sensor Observation Service (SOS)_2.0
Last Month:6    |   Last 3 Months:6     |   Last Year:6 |   All Times:6

Test Name: Web Coverage Service (WCS)_1.1.1
Last Month:3    |   Last 3 Months:3     |   Last Year:3 |   All Times:3

...

est Statistics by Users

Test Name: Catalogue Service - Web (CSW)_3.0.0
Last Month:6    |   Last 3 Months:6     |   Last Year:6 |   All Times:6

Test Name: Sensor Observation Service (SOS)_2.0
Last Month:2    |   Last 3 Months:2     |   Last Year:2 |   All Times:2

Test Name: Web Coverage Service (WCS)_1.1.1
Last Month:3    |   Last 3 Months:3     |   Last Year:3 |   All Times:3

Test Name: Web Map Tile Service (WMTS)_1.0.0
Last Month:16   |   Last 3 Months:16        |   Last Year:16    |   All Times:16

Test Name: Web Processing Service (WPS)_1.0.0
Last Month:12   |   Last 3 Months:12        |   Last Year:12    |   All Times:12

**Comment by bermud** [comment]
Please make sure the date comes from the session.xml. As discussed before you can use the 'date' attribute. I will send you the link to sample data via email.

**Comment by keshavnangare** [comment]
Fixed with this commit e722a78c6d316f1e2037d22191ea16c1e6a4dea5

**Comment by bermud** [comment]
Need verification

**Comment by bermud** [comment]
This is correct now.
