### ISSUE TITLE
WFS 2.0 is missing from the results

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#6]
When running the results WFS 2.0 statistics were not part of the output.

**Comment by keshavnangare** [comment]
The script will run in the following way:
1. The script will take the list of test-suite name from the config.xml which is present in "C:\TE_BASE\config.xml". 
2. The script will iterate the test-suite one-by-one and traverse through the each user session ( From C:\TE_BASE\users\ ) and result is displayed with the stats of each tests.

Note: 
         For example if s0002 (WFS2.0) is a session which is present in the session directory (C:\TE_BASE\users\ogctest\s0002) and if WFS 2.0 standard is not present in the config file ( C:\TE_BASE\config.xml ), 
then it  will not appear in the report even if the session is present in the users directory.

**Comment by bermud** [comment]
WFS 2.0 is present in the config file. Here it is
http://cite.opengeospatial.org/pub/cite/files/config.xml-20160608.zip

**Comment by keshavnangare** [comment]
Fixed with this commit: a3c5d916af4a7970fbd59d33456601b76bdb92de
