### ISSUE TITLE
Change the report output

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#8]
Provide a report that creates a file that is comma separated value with the following information:

userName | session | date | testName | overallResult

**The test should be short texts as follows:**
- CSW202
- WMS13
- WFS20
- WFS110
- GML321
- KML22
- WCS11

**The overall result should be:**
- failed
- not completed
- passed
- partial passed

**The file name should be as follows:**

teamengine-statistics-yyyymmdd-hhss

**Comment by keshavnangare** [comment]
@Luis

How we can get the overall result from the session directory? Whether it is passed, failed or not completed.

**Comment by bermud** [comment]
Each folder contains a log.xml that has an "endtest" tag if it is =1 it has paased all the tests.

<endtest result="1"/> is pass ! 

If there is no result, probably the test was not completed. 

From  the Java code:

public static final int CONTINUE = -1;
public static final int BEST_PRACTICE = 0;
public static final int PASS = 1;
public static final int NOT_TESTED = 2;
public static final int SKIPPED = 3;
public static final int WARNING = 4;
public static final int INHERITED_FAILURE = 5;
public static final int FAIL = 6;

**Comment by keshavnangare** [comment]
Thanks Luis.

**Comment by keshavnangare** [comment]
Updated the report with this commit: f6cab7204fb97c090aa33c3a32b4421e0483ffed
